# Begin Project
project:
  type: tutorial-template
  # FYI: the tutorial-template project type is defined in the lmu-osc/tutorial-template extension
# End Project

# Begin Website
repo-url: https://github.com/lmu-osc/introduction-to-zotero
website:
  title: "Introduction to Zotero"
  page-footer:
    border: false
    center: © 2024 Pat Callahan, Dejana Damjanovic. Published by LMU Open Science Center. Licensed under CC BY-SA 4.0.
  repo-url: https://github.com/lmu-osc/introduction-to-zotero

  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/lmu-osc/introduction-to-zotero
          - text: Report a Bug
            href: https://github.com/lmu-osc/introduction-to-zotero/issues
      - icon: house-heart
        url: https://www.osc.lmu.de/

  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Background"
        href: background/index.qmd
        contents:
          - href: background/zotero-basics.qmd
            text: "Zotero Basics"
          - href: background/zotero-usage.qmd
            text: "Zotero Usage"
          - href: background/citation-style-language.qmd
            text: "Citation Style Language"
      - section: "Integrating Zotero"
        href: integrating-zotero/index.qmd
        contents:
          - href: integrating-zotero/citations-in-quarto.qmd
            text: "Citations in Quarto"
          - href: integrating-zotero/citations-in-word.qmd
            text: "Citations in Word"
      - text: "Best Practices"
        href: background/best-practices.qmd
      - section: "Exercises"
        href: exercises/index.qmd
        contents:
          - href: exercises/use-zotero.qmd
            text: "Basic Zotero Usage"
          - href: exercises/quarto-citations.qmd
            text: "Integrating with Quarto"
          - href: exercises/change-csl.qmd
            text: "Changing CSL"
      - section: "Advanced"
        href: advanced/index.qmd
        contents:
          - href: advanced/zotero-groups.qmd
            text: "Zotero Groups"
          # - href: advanced/zotero-plugins.qmd
          #   text: "Zotero Plugins"
# End Website

# Begin Includes
include-in-header:
  - file: matomo-analytics.html
# End Includes

# Begin Format
# use only if needed. the default format for `tutorial-template` projects is tutorial-template-html+tutorial
# we recommend just extending the definition below if you need to make format changes
format:
  tutorial-template-html+tutorial:
    css:
      - footer/footer-style.css
    include-after-body:
      - file: footer/footer.html
# End Format

# Begin Editor
editor: source
# End Editor

bibliography: references.bib
