project:
  type: website

website:
  title: "Introduction to Zotero"
  page-footer:
    center: "Copyright, 2024 Open Science Center at LMU Munich"
    border: false
  search:
    location: sidebar
  repo-url: https://github.com/lmu-osc/introduction-to-zotero
  repo-actions: [edit, issue]
  back-to-top-navigation: true
  page-navigation: true
  favicon: assets/lmu-osc-favicon.jpg
  margin-header: |
    ![](/assets/lmu-osc-logo.svg){width="175"}

  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/lmu-osc/introduction-to-zotero
          - text: Report a Bug
            url: https://github.com/lmu-osc/introduction-to-zotero/issues
      - icon: house-heart
        url: https://www.osc.lmu.de/

  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Background"
        href: background/index.qmd
        contents:
          - href: background/zotero-basics.qmd
            text: "Zotero Basics"
          - href: background/zotero-usage.qmd
            text: "Zotero Usage"
          - href: background/citation-style-language.qmd
            text: "Citation Style Language"
      - section: "Integrating Zotero"
        href: integrating-zotero/index.qmd
        contents:
          - href: integrating-zotero/citations-in-quarto.qmd
            text: "Citations in Quarto"
          - href: integrating-zotero/citations-in-word.qmd
            text: "Citations in Word"
      - text: "Best Practices"
        href: background/best-practices.qmd
      - section: "Exercises"
        href: exercises/index.qmd
        contents:
          - href: exercises/use-zotero.qmd
            text: "Basic Zotero Usage"
          - href: exercises/quarto-citations.qmd
            text: "Integrating with Quarto"
          - href: exercises/change-csl.qmd
            text: "Changing CSL"
      - section: "Advanced"
        href: advanced/index.qmd
        contents:
          - href: advanced/zotero-groups.qmd
            text: "Zotero Groups"
          # - href: advanced/zotero-plugins.qmd
          #   text: "Zotero Plugins"

format:
  html:
    theme:
      - cosmo
      - lmu-osc-custom.scss
    css:
      - assets/bootstrap-grid.min.css
      - https://raw.githubusercontent.com/lmu-osc/branding-resources/refs/heads/main/lmu-osc-styles.css
      - footer/footer-style.css
    toc: true
    fontsize: 13pt
    code-overflow: wrap
    grid:
      sidebar-width: 300px
    include-in-header:
      - file: matomo-analytics.html

bibliography: references.bib
