project:
  type: website


website:
  title: "Introduction to Zotero"
  page-footer:
    center: "Copyright, 2024 Open Science Center at LMU Munich"
    border: false
  search:
    location: sidebar
  repo-url: https://github.com/lmu-osc/introduction-to-zotero
  repo-actions: [edit, issue]
  back-to-top-navigation: true
  page-navigation: true
  favicon: assets/LMU-OSC_favicon.jpg
  margin-header: |
    ![](/assets/LMU-OSC_logo.jpg){width="175"}


  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/lmu-osc/introduction-to-zotero
          - text: Report a Bug
            url:  https://github.com/lmu-osc/introduction-to-zotero/issues
      - icon: house-heart
        url: https://www.osc.uni-muenchen.de/index.html


  sidebar:
    style: "docked"
    # background: "#cfc7c6"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Background"
        contents:
          - href: background/zotero_basics.qmd
            text: "Zotero Basics"
          - href: background/zotero_usage.qmd
            text: "Zotero Usage"
          - href: background/citation_style_language.qmd
            text: "Citation Style Language"
      - section: "Integrating Zotero"
        contents:
          - href: integrating_zotero/citations_in_quarto.qmd
            text: "Citations in Quarto"
          - href: integrating_zotero/citations_in_word.qmd
            text: "Citations in Word"
      - section: "Exercises"
        contents:
          - href: exercises/exercise_1.qmd
            text: "Exercise 1: Using Zotero"
          - href: exercises/exercise_2.qmd
            text: "Exercise 2: Integrating with Quarto"
          - href: exercises/exercise_3.qmd
            text: "Exercise 3: Changing CSL"
      - section: "Advanced"
        contents:
          - href: advanced/zotero_groups.qmd
            text: "Zotero Groups"
          # - href: advanced/zotero_plugins.qmd
          #   text: "Zotero Plugins"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    fontsize: 13pt
    code-overflow: wrap
    grid:
      sidebar-width: 300px
    include-in-header:
      - file: matomo-analytics.html


