---
title: "About"
date: 2024-11-29
citation:
  type: "webpage"
  title: "Introduction to Zotero"
  container-title: "LMU Open Science Center"
  url: https://lmu-osc.github.io/introduction-to-zotero
  doi: "10.5281/zenodo.14243118"
  version: v0.1.1
author:
  - name: Pat Callahan
    roles: [conceptualization, data curation, formal analysis, funding acquisition, investigation, methodology, project administration, software, resources, supervision, validation, visualization, writing - original draft, writing - editing & review]
    degrees:
      - B.S.
      - M.Sc.
      - PhD
    affiliation: 
      - id: osc
        name: LMU Open Science Center
        ror: https://ror.org/05591te55
        isni: 000000041936973X
      - id: ibe
        name: LMU Institute for Medical Information Processing, Biometry, and Epidemiology (IBE)
    orcid: 0000-0003-0374-5625
  - name: Dejana Damjanovic
    roles: [conceptualization, writing - original draft, writing - editing & review]
    affiliation:
      - id: osc
        name: LMU Open Science Center
        ror: https://ror.org/05591te55
        isni: 000000041936973X
    orcid: 0009-0000-6912-1140
# google-scholar: true
---

## Contributors

This site was authored by Pat Callahan, and edits/contributions were made by Dejana Damjanovic (who primarily authored the "Zotero Groups" chapter).

## Licenses

The overall project is available under the [**CC BY-SA 4.0**](https://creativecommons.org/licenses/by-sa/4.0/) license found at [LICENSE](LICENSE.md); all code without any narrative text is also (at your option) available under the [**CC0 1.0 Universal**](https://creativecommons.org/publicdomain/zero/1.0/) license found at [LICENSE-CODE](LICENSE-CODE.md).

Why two licenses? The CC BY-SA 4.0 license is for the content of the website, while the CC0 1.0 Universal license is for the code and configuration files. This is a common practice for websites that include code snippets and other content that may be reused in other projects, particularly because the CC BY-SA 4.0 license is not intended to be used with software.

## Notes

This tutorial was primarily written in 2024 using Zotero versions 6.0.3X through the major 7.0.10 release. Major changes to Zotero can be found at the [Zotero changelog](https://www.zotero.org/support/changelog), and to confirm that our tutorial is not out-of-date.

## Tutorial Template Quarto Extension

This tutorial was written using the [`lmu-osc/tutorial-template`](https://github.com/lmu-osc/tutorial-template) Quarto extension [@callahan2026].

::: {#refs}
:::

## How to Cite

**To cite this tutorial, please refer to the project's [CITATION.cff](CITATION.cff) file or use the BibTeX citation provided in the appendix below.**
