---
title: "Citations in Quarto"
format: html
bibliography: references.bib
---

The instructions on this page largely rely on the use of RStudio. If you are not using RStudio, you should note that whatever text editor you are using may not have the same functionality, and you may need to adjust your workflow accordingly. That said, these instructions also cover text-only editing options that should be viable approaches to editing your document via any text editor.

One of the benefits of using RStudio is that it will automatically generate a bibliography file for you when you insert a citation. This bibliography file will be automatically updated to include any new citations you add, and it will automatically generate the bibliography in the format you specify in the YAML of your file.

For other text editors, you must first generate your bibliography file, and then manually add the bibliography to the project directory and the yaml header of your file. You will also need to manually update the bibliography file to include any new citations you add.

If you choose to stick with a different text editor, you can check out the [Tutorial: Authoring](https://quarto.org/docs/get-started/authoring/text-editor.html#citations) Quarto documentation page for more information.

# Inserting Citations

To insert an in-line citation in your document, you will need to use the source's "citation key" which is a unique identifier for each reference in your Zotero library. This citation key connects your citation to the correct entry in the `references.bib` file.

The citation keys generated by RStudio typically follow the format `@authorYear` or `@authorYearLetter` when there are multiple matches, but they can be customized to your liking. If you *export* a library from Zotero, however, a different default method for generating the citation keys will be used. These differences will be discussed in the following sub-sections, [RStudio Visual Editor](#rstudio-visual-editor) and [Manual Entry](#manual-entry).

You can insert a citation in your document by using the `@` symbol followed by the citation key of the reference you want to cite. For example, I have saved the Zotero Quick Start guide to my Zotero library for this tutorial, and in order to to cite this guide, I would use the citation key `[@zotero]` in my document:

> "Items can be assigned tags. Tags are named by the user. An item can be assigned as many tags as is needed."**[\@zotero]**

This will insert a citation in your document that looks like this: 

> "Items can be assigned tags. Tags are named by the user. An item can be assigned as many tags as is needed."**[@zotero]**

Note that the citation key can be inserted in two ways: with or without brackets `[]`, which yield formatting differences. A citation without brackets, `@zotero`, will appear inline as "@zotero", while a citation with brackets, `[@zotero]`, will appear as "[@zotero]".

::: {.callout-tip title="Citation Keys"}

The citation keys used in RStudio use Pandoc citation syntax. You can find more information on Pandoc citation syntax in the Pandoc documentation on [citations](https://pandoc.org/MANUAL.html#citations) and [citation syntax](https://pandoc.org/MANUAL.html#citation-syntax).

:::



## RStudio Visual Editor





## Manual Entry

This will insert a citation in your document that looks like this: \[\@zotero\].

The first time you insert a citation, a `references.bib` file should be generated in the same directory as your document. This file will contain the citation information for the references you have cited in your document.

# Adding a Bibliography

-   bibliography does not automatically update if you update the references in Zotero. you may need to delete the `references.bib` file and reinsert the citations to update the bibliography. this sounds a bit complicated, but simply deleting the `references.bib` file and reinserting a single citation will prompt RStudio to regenerate the `references.bib` file with the updated references.
-   an issue requesting that the bibliography automatically update when references are updated in Zotero was previosuly opened in the RStudio GitHub repository, but it was closed without being addressed. you can find the issue [here](https://github.com/rstudio/rstudio/issues/11447). you can, however, comment that you'd like to see this feature implemented in the future ;).

## Adding to YAML

To add a bibliography to your document, you will need to include a YAML metadata block at the beginning of your document that specifies the citation style you want to use. You can find a list of supported citation styles [here](https://citationstyles.org/).

For example, to add a bibliography in APA style, you would include the following YAML metadata block at the beginning of your document:

``` yaml
---
title: "My Document"
bibliography: references.bib
---
```

This will generate a bibliography at the end of your document that includes all of the references you have cited in your document.

## Adding References at the End of the Document

https://quarto.org/docs/authoring/citations.html#bibliography-generation

# Changing Citation Style

Here is an example of a document that includes citations and a bibliography:

``` yaml
---
title: "My Document"
bibliography: references.bib
csl: your-csl-file.csl
---
```

# Example Video

# References

::: {#refs}
:::
