---
title: "Welcome to the Zotero Tutorial!"
subtitle: A self-paced introduction to Zotero for organizing references and citing in RStudio, Quarto, and Word
description: Learn how to use Zotero to organize your research, create bibliographies, and integrate citations with Quarto and Microsoft Word.
---

```{r}
#| eval: true
#| echo: false
#| warning: false
library(downlit)
library(xml2)
```

## Tutorial Overview

This self-paced tutorial will introduce you to Zotero, a free citation management tool that can help you organize your research and create bibliographies with a specific focus on integrating it with RStudio and Quarto. It is intended to take about 30-60 minutes to complete.

The tutorial is split into the following sections:

1. [Getting Started with Zotero](background/zotero-basics.qmd)
2. [Integrating Zotero](integrating-zotero/citations-in-quarto.qmd)
3. [Exercises](exercises/use-zotero.qmd)
4. [Advanced](advanced/zotero-groups.qmd)

::: {.callout-tip title="Software Requirements"}

To complete this tutorial, you will need to have the following software installed on your computer:

- [Zotero and Zotero Connector](https://www.zotero.org/download/)
- [RStudio](https://www.rstudio.com/products/rstudio/download/)
- [Quarto](https://quarto.org/docs/get-started/)
  - **RStudio comes bundled with Quarto. You do not need to install Quarto separately if you have a recent version of RStudio.**

:::


::: {.callout-tip title="Exercises"}

We recommend completing all of the steps outlined in the Background and Integrating Zotero sections of this tutorial *as you read through them.* The Exercises section of this tutorial essentially rehashes the same content, but is intended to review and consolidate the topics discussed.

Moreover, while this tutorial can be completed with any code text editor, we highly recommend using RStudio because it is well-integrated with Zotero.

:::


:::: {.columns}

::: {.column width="47.5%"}

::: {.callout-tip title="Support the LMU Open Science Center!"}

**Like this tutorial? Be sure to give [the repository]({{< meta repo-url >}}) a star and [follow us on GitHub](https://github.com/lmu-osc)!**
:::

:::

::: {.column width="5%"}
:::

::: {.column width="47.5%"}


::: {.callout-tip title="Questions about this tutorial?"}
**If you have questions for the author of this tutorial, please take a look at the [About](about.qmd) page.**
:::

:::

::::
